name: language-sml
version: 0.1.0.0
github: "githubuser/language-sml"
license: BSD3
author: "Author name here"
maintainer: "example@example.com"
copyright: "2020 Author name here"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/language-sml#readme>

dependencies:
  - base-noprelude
  - relude
  - array
  - containers
  - megaparsec
  - mtl
  - parser-combinators
  - pretty-simple
  - prettyprinter
  - scientific
  - text
  - unordered-containers
  - vector

default-extensions:
  # Basics
  - FlexibleContexts
  - FlexibleInstances
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - MultiParamTypeClasses
  - ScopedTypeVariables
  - StrictData
    # Ergonomics
  - DuplicateRecordFields
  - LambdaCase
  - NamedFieldPuns
  - OverloadedStrings
  - RecordWildCards
  - TupleSections
    # Deriving
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
    # Typeclasses
  - FunctionalDependencies
  - KindSignatures
  - TypeOperators
    # Fancier bois
  - DataKinds
  - GADTs
  - RankNTypes
  - TypeFamilies
    # Random stuff
  - AllowAmbiguousTypes
  - ApplicativeDo
  - BangPatterns
  - ConstraintKinds
  - DefaultSignatures
  - MultiWayIf
  - NoMonomorphismRestriction
  - TypeApplications

library:
  source-dirs: src
  exposed-modules:
    - Language.Sml
    - Language.Sml.Ast.Associativity
    - Language.Sml.Ast.Decl
    - Language.Sml.Ast.Expr
    - Language.Sml.Ast.Ident.Common
    - Language.Sml.Ast.Ident.Label
    - Language.Sml.Ast.Ident.Long
    - Language.Sml.Ast.Ident.Op
    - Language.Sml.Ast.Ident.StructureIdent
    - Language.Sml.Ast.Ident.TyCon
    - Language.Sml.Ast.Ident.TyVar
    - Language.Sml.Ast.Ident.ValueIdent
    - Language.Sml.Ast.Lit
    - Language.Sml.Ast.Lit.Character
    - Language.Sml.Ast.Pat
    - Language.Sml.Ast.Typ
    - Language.Sml.Common.Marked
    - Language.Sml.Common.Position
    - Language.Sml.Common.Positive
    - Language.Sml.Lexer
    - Language.Sml.Lexer.Token
    - Language.Sml.Parser
    - Language.Sml.Parser.DebugLevel
    - Language.Sml.Pretty
    - Language.Sml.Pretty.Comments
  ghc-options:
    - -Wall
    - -foptimal-applicative-do
    - -O2

tests:
  language-sml-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - language-sml
